# Site settings
title: 
header-img: img/home-bg.png
email: macciak@gmail.com
copyright_name: gosherama
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: macciak
github_username:  gosherama
learn_profile: gosherama
email_username: macciak@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
